[package]
name = "embassy-nats"
version = "0.1.0"
edition = "2024"
authors = [ "Eliseo Cailloux" ]

[features]
alloc = []

[dependencies]

embassy-sync = { version = "0.8.0" }
embassy-futures = { version = "0.1.2" }
embassy-net = { version = "0.9.1", features = ["defmt", "tcp", "dhcpv4", "proto-ipv4", "proto-ipv6" ] }
embedded-io-async = "0.7.0"

defmt = "1.1"

thiserror = { version = "2.0.20", default-features = false }

serde = { version = "1.0.229", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.6.0", features = ["defmt"] }
heapless = { version = "0.9.3", features = ["serde"] }

[profile.release]
debug = 2
