[package]
name = "embassy-nats"
version = "1.0.0"
edition = "2024"
authors = [ "Eliseo Cailloux" ]

[features]
alloc = []
defmt = [ "dep:defmt", "embassy-sync/defmt", "embassy-futures/defmt", "embassy-net/defmt", "serde-json-core/defmt" ]

[dependencies]

embassy-sync = { git = "https://github.com/Eleocraft/embassy.git", branch = "embassy_boot_crypto" }
embassy-futures = { git = "https://github.com/Eleocraft/embassy.git", branch = "embassy_boot_crypto" }
embassy-net = { git = "https://github.com/Eleocraft/embassy.git", branch = "embassy_boot_crypto", features = ["tcp", "dhcpv4", "ipv4", "ipv6" ] }
embedded-io-async = "0.7.0"

serde = { version = "1.0.229", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.6.0" }
heapless = { version = "0.9.3", features = ["serde"] }

thiserror = { version = "2.0.20", default-features = false }

defmt = { version = "1.1", optional = true }
portable-atomic = "1.15.0"

[profile.release]
debug = 2
